### ISSUE TITLE
Character file provided can be confusing

### ISSUE THREAD

**Issue by Zheng-Kevin** [Alchyr/BasicMod#6]
Using winrar, the character.zip file provided here(https://github.com/Alchyr/BasicMod/wiki/Adding-a-character) unzip to a folder called character and includes a folder called character. When moving the unzipped file, intelliJ will create a folder called character.character. I suggest renaming the zipped file to something else, like sample character or something. 
![image](https://github.com/Alchyr/BasicMod/assets/34946315/e8df3180-68fb-4ba8-b37f-52ba70e7d259)

**Comment by Alchyr** [comment]
👍
