### ISSUE TITLE
About modID

### ISSUE THREAD

**Issue by kelibkali** [Alchyr/BasicMod#9]
For aesthetic reasons, what should I do if I don’t want the modID to appear in front of the keyword in the game?

**Comment by Alchyr** [comment]
if set up properly, it shouldn't

If the keyword is highlighted properly (generates a tooltip on the card) but the prefix is not automatically hidden, there can be a few possible causes

Most likely one is that if language is zhs, certain capitalized letters in the mod ID can cause issues

**Comment by kelibkali** [comment]
It is indeed a problem caused by capital letters in the zhs language
With your help, my problem has been solved, thank you
thank you for your high-quality code
wish you a happy life ^_^

**Comment by Alchyr** [comment]
👍
